nlp$cfg:
  stanford:
    url: http://media.local:18081
    token: some-token
pipeline:
  folder: .pipeline

  handlers:
  - extensions: .txt

  actions:
  - document.encoding
  - document.crlf

  - stanford.tokenize.entities
  - stanford.tokenize.syntax
  - method: tokens.merge
    inject:
      keys:
      - stanford.tokenize.entities
      - stanford.tokenize.syntax

  - extract.persons
  - extract.places
  - extract.organizations
  - method: entities.merge
    inject:
      keys:
      - extract.persons
      - extract.places
      - extract.organizations

  - method: document.write.json
    name: entities.yaml
    key: entities
